# Warnings currently triggered by your code
- ignore: {name: "Use camelCase"} # 10 hints

# For some tests we want to write code that triggers HLint.
- ignore: {name: "Avoid reverse", within: [Lists]}

# False positive?
- ignore: {name: "Redundant seq"}
