name: Continuous integration
on:
  pull_request:
  push:
env:
  # Bump this number to invalidate the GH actions cache
  cache-version: 0

jobs:
  test-nixpkgs:
    name: Build & Test - Nixpkgs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v12
        with:
          nix_path: nixpkgs=./nixpkgs.nix
      - name: Mount dependency cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            .stack-work
          key: stack-cache-${{ runner.os }}-${{ env.cache-version }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('nixpkgs.nix') }}
      - name: Build & test
        run: nix-shell --pure --run "stack --nix test --pedantic"
